swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
paths:
  /users-auth/login:
    post:
      tags:
        - users-auth
      summary: User Login
      operationId: userLogin
      description: Authenticate user and generate access token and refresh token.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loginCredentials
          description: User login credentials
          required: true
          schema:
            type: object
            properties:
              UserName:
                type: string
                example: "adminDONGTAC"
              PassWord:
                type: string
                example: "1"
              MaDV:
                type: string
                example: "DONGTAC"
      responses:
        200:
          description: Successful login
          schema:
            type: object
            properties:
              accessToken:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              refreshToken:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        401:
          description: Unauthorized - Invalid credentials
        500:
          description: Internal Server Error - Unable to process the request

